/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AccountAggregatorRouteImport } from './routes/account-aggregator';
import { Route as AnalysisRouteImport } from './routes/analysis';
import { Route as CoachRouteImport } from './routes/coach';
import { Route as DebtRouteImport } from './routes/debt';
import { Route as InsightsRouteImport } from './routes/insights';
import { Route as KnowRouteImport } from './routes/know';
import { Route as LifeEventsRouteImport } from './routes/life-events';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as PlansRouteImport } from './routes/plans';
import { Route as PortfolioRouteImport } from './routes/portfolio';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as ScoreRouteImport } from './routes/score';
import { Route as TransferRouteImport } from './routes/transfer';
import { Route as Wealth360RouteImport } from './routes/wealth360';
import { Route as WealthverseBusinessRouteImport } from './routes/wealthverse-business';
import { Route as WelcomeRouteImport } from './routes/welcome';
import { Route as GoalsIndexRouteImport } from './routes/goals.index';
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId';
import { Route as Wealth360AnalysisRouteImport } from './routes/wealth360.analysis';
import { Route as Wealth360DashboardRouteImport } from './routes/wealth360.dashboard';
import { Route as Wealth360JourneyRouteImport } from './routes/wealth360.journey';
import { Route as Wealth360ReviewRouteImport } from './routes/wealth360.review';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
});
const AccountAggregatorRoute = AccountAggregatorRouteImport.update({
  id: '/account-aggregator',
  path: '/account-aggregator',
  getParentRoute: () => rootRouteImport
});
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport
});
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport
});
const DebtRoute = DebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => rootRouteImport
});
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport
});
const KnowRoute = KnowRouteImport.update({
  id: '/know',
  path: '/know',
  getParentRoute: () => rootRouteImport
});
const LifeEventsRoute = LifeEventsRouteImport.update({
  id: '/life-events',
  path: '/life-events',
  getParentRoute: () => rootRouteImport
});
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport
});
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport
});
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport
});
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport
});
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport
});
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport
});
const Wealth360Route = Wealth360RouteImport.update({
  id: '/wealth360',
  path: '/wealth360',
  getParentRoute: () => rootRouteImport
});
const WealthverseBusinessRoute = WealthverseBusinessRouteImport.update({
  id: '/wealthverse-business',
  path: '/wealthverse-business',
  getParentRoute: () => rootRouteImport
});
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport
});
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport
});
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport
});
const Wealth360AnalysisRoute = Wealth360AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => Wealth360Route
});
const Wealth360DashboardRoute = Wealth360DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Wealth360Route
});
const Wealth360JourneyRoute = Wealth360JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => Wealth360Route
});
const Wealth360ReviewRoute = Wealth360ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => Wealth360Route
});






























































































































































































































































































































































const Wealth360RouteChildren = {
  Wealth360AnalysisRoute: Wealth360AnalysisRoute,
  Wealth360DashboardRoute: Wealth360DashboardRoute,
  Wealth360JourneyRoute: Wealth360JourneyRoute,
  Wealth360ReviewRoute: Wealth360ReviewRoute
};

const Wealth360RouteWithChildren = Wealth360Route._addFileChildren(
  Wealth360RouteChildren
);

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountAggregatorRoute: AccountAggregatorRoute,
  AnalysisRoute: AnalysisRoute,
  CoachRoute: CoachRoute,
  DebtRoute: DebtRoute,
  InsightsRoute: InsightsRoute,
  KnowRoute: KnowRoute,
  LifeEventsRoute: LifeEventsRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ScoreRoute: ScoreRoute,
  TransferRoute: TransferRoute,
  Wealth360Route: Wealth360RouteWithChildren,
  WealthverseBusinessRoute: WealthverseBusinessRoute,
  WelcomeRoute: WelcomeRoute,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsIndexRoute: GoalsIndexRoute
};
export const routeTree = rootRouteImport.
_addFileChildren(rootRouteChildren).
_addFileTypes();